### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7b1d4b2038de80c7c6507a09fa4f027ea516b362
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://gitcop.com/Gazler/changex/guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7b1d4b2038de80c7c6507a09fa4f027ea516b362
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://gitcop.com/Gazler/changex/guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by Gazler** [comment]
Thanks <3

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
